apiVersion: v1
kind: Service
metadata:
  name: vpkg-registry-service
  namespace: wooglife
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: NodePort
  selector:
    app: vpkg-registry
  ports:
    - name: http
      protocol: TCP
      port: 61110
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpkg-registry
  namespace: wooglife
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vpkg-registry
  template:
    metadata:
      labels:
        app: vpkg-registry
    spec:
      containers:
      - name: vpkg-registry
        image: woog-life/vpkg-registry:{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
